### ISSUE TITLE
reloading app in development mode, still plays audio

### ISSUE THREAD

**Issue by sanihaq** [erikas-taroza/simple_audio#9]
It's not a big issue but...
after reloading, some function still works like volume control but some doesn't like play,pause.
is there way to hook into a already playing audio instance?
what is the process looks like if i want to close the application but keep the audio playing and upon reopening hook into the previous instance of `SimpleAudio`. is that possible?

need a way to `dispose` a player (i.e. `dispose()` method).

**Comment by erikas-taroza** [comment]
> It's not a big issue but...
> after reloading, some function still works like volume control but some doesn't like play,pause.

 I will fix this issue.



> is there way to hook into a already playing audio instance?
> what is the process looks like if i want to close the application but keep the audio playing and upon reopening hook into the previous instance of `SimpleAudio`. is that possible?

This will not be implemented. If the user closes the app, they expect anything that the app was doing (ex. playing audio) to also stop.

**Comment by erikas-taroza** [comment]
Hello @sanihaq.

I have to write some platform code for macOS and iOS before I can merge #10. Unfortunately, I don't have access to a Mac or iPhone because I am travelling.  You can expect this bug to be fully fixed in March 9 or 10. Sorry for the delay.

I can run the CI to build the Android and Linux libraries so you can start using the supported platforms. Let me know if you would like that.
